# Generated by Django 5.0.3 on 2024-03-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegNo', models.IntegerField(max_length=10)),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('Phone', models.IntegerField(max_length=10)),
                ('Domian', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='StudentModel',
        ),
    ]
