# Generated by Django 5.0.3 on 2024-03-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0002_teachersmodel_delete_studentmodel'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='teachersmodel',
            name='Teachers_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teachersmodel',
            name='Phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='teachersmodel',
            name='RegNo',
            field=models.IntegerField(),
        ),
    ]
