# Generated by Django 5.0.3 on 2024-03-10 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0003_remove_teachersmodel_id_teachersmodel_teachers_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachersmodel',
            name='Teachers_id',
        ),
    ]
